# Diretório raiz do projeto (onde está o .air.toml)
root = "."

# Onde o binário temporário será gerado
bin = "tmp/main"

# Comando para buildar o projeto (gera o binário)
cmd = "go build -o ./tmp/main ./cmd/api"

# Comando para rodar o binário após o build
full_bin = "tmp/main"

# Diretório temporário usado pelo Air
tmp_dir = "tmp"

[build]
# Monitora tudo (exceto tmp e vendor)
include_ext = ["go", "env", "yaml", "toml", "json"]
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test\\.go"]

# Exibe logs coloridos
color = true

